<?php

declare(strict_types=1);

return [
    'titles' => [
        'bigIncrements',
        'bigInteger',
        'integer',
        'mediumInteger',
        'smallInteger',
        'tinyInteger',
        'unsignedBigInteger',
        'unsignedInteger',
        'unsignedMediumInteger',
        'unsignedSmallInteger',
        'unsignedTinyInteger',
        'increments',
        'mediumIncrements',
        'smallIncrements',
        'tinyIncrements',
        'string',
        'char',
        'text',
        'mediumText',
        'longText',
        'tinyText',
        'binary',
        'date',
        'dateTime',
        'dateTimeTz',
        'time',
        'timeTz',
        'timestamp',
        'timestampTz',
        'year',
        'json',
        'jsonb',
        'lineString',
        'rememberToken',
    ],
    'types' => [
        'bigIncrements' => 'int',
        'bigInteger' => 'int',
        'integer' => 'int',
        'mediumInteger' => 'int',
        'smallInteger' => 'int',
        'tinyInteger' => 'int',
        'unsignedBigInteger' => 'int',
        'unsignedInteger' => 'int',
        'unsignedMediumInteger' => 'int',
        'unsignedSmallInteger' => 'int',
        'unsignedTinyInteger' => 'int',
        'increments' => 'int',
        'mediumIncrements' => 'int',
        'smallIncrements' => 'int',
        'tinyIncrements' => 'int',
        'string' => 'string',
        'char' => 'string',
        'text' => 'string',
        'mediumText' => 'string',
        'longText' => 'string',
        'tinyText' => 'string',
        'binary' => 'string',
        'date' => 'CarbonInterface',
        'dateTime' => 'CarbonInterface',
        'dateTimeTz' => 'CarbonInterface',
        'time' => 'CarbonInterface',
        'timeTz' => 'CarbonInterface',
        'timestamp' => 'CarbonInterface',
        'timestampTz' => 'CarbonInterface',
        'year' => 'string',
        'json' => 'array',
        'jsonb' => 'array',
        'lineString' => 'array',
        'rememberToken' => 'string|null',
    ],
];
